// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/caderneta/Redesign.tsx": () => import("../components/mockups/caderneta/Redesign.tsx"),
  "./components/mockups/painel-principal/BoldDashboard.tsx": () => import("../components/mockups/painel-principal/BoldDashboard.tsx"),
  "./components/mockups/painel-principal/CommandCentre.tsx": () => import("../components/mockups/painel-principal/CommandCentre.tsx"),
  "./components/mockups/painel-principal/NeoAcademia.tsx": () => import("../components/mockups/painel-principal/NeoAcademia.tsx")
};
